config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    resources :votes
  end
  resources :users do
    resources :followers
  end
  resources :usersessions

  delete "logout", to: "usersessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :user_id, class_name: :User
  belongs_to :following, foreign_key: :follower_id, class_name: :User

  validates_uniqueness_of :follower_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :votes, dependent: :destroy

  validates :content, presence: true, length: { maximum: 50 }

  def voted
    votes.where(voted: true)
  end

  def unvoted
    votes.where(voted: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_one_attached :cover
  has_many :posts, foreign_key: :author_id, dependent: :destroy

  has_many :follows, dependent: :destroy

  has_many :follower_user, foreign_key: :follower_id, class_name: :Follow
  has_many :followers, through: :follower_user, source: :follower

  has_many :following_user, foreign_key: :user_id, class_name: :Follow
  has_many :following, through: :following_user, source: :following

  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true

  has_many :votes, foreign_key: :voter_id, dependent: :destroy

  def following?(user)
    following.include?(user)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voter, class_name: :User, foreign_key: :voter_id
  belongs_to :post, class_name: :Post, foreign_key: :post_id

  validates :voter_id, :post_id, presence: true
  validates_uniqueness_of :post_id, scope: :voter_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def authenticate_user!
    redirect_to new_usersession_path unless current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.includes([:image_attachment]).find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def create
    @follower = Follow.new(user_id: current_user.id)
    @follower.follower_id = params[:user_id]
    if @follower.save
      redirect_to posts_path
    else
      redirect_to posts_path, alert: 'Error!'
    end
  end

  def destroy
    @follower = Follow.find_by(follower_id: params[:user_id], user_id: params[:id])
    @follower ||= Follow.find_by(follower_id: params[:id], user_id: current_user.id)
    if @follower.destroy
      redirect_to posts_path
    else
      head :no_content
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @followers = current_user.following.map(&:id).push(current_user.id)
    @users = User.where.not(id: @followers).includes(image_attachment: :blob).order('id DESC')
    @posts = Post.where(author_id: @followers).includes(author: [image_attachment: :blob]).order('id DESC')
  end

  def show
    @post = Post.find(params[:id]).includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Post was successfully destroyed.'
      redirect_to posts_url
    else
      flash[:alert] = 'Post deletion failed'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[new create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.includes([image_attachment: :blob]).includes([:cover_attachment])
      .includes(followers: [image_attachment: :blob]).includes(following: [image_attachment: :blob])
      .includes(posts: [:author]).find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(cover: params[:cover])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:posts).includes([:image_attachment]).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user).permit(:name, :username, :email, :image)
  end
end

app/controllers/usersessions_controller.rb
class UsersessionsController < ApplicationController
  def new
    @session = User.new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:alert] = 'Please check your username!'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to posts_path
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @votes = Vote.new(voter_id: current_user.id, post_id: params[:post_id],
                      voted: params[:voted])
    if @votes.save
      redirect_to posts_path
    else
      head :no_content
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    if @vote.destroy
      redirect_to posts_path
    else
      head :no_content
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def new_vyews(post)
    posts = post.select { |p| p.created_at.to_date == Date.current }.size
    if posts == 1
      '1 new vyew'
    else
      "#{posts} new vyews"
    end
  end

  def like(post)
    user = post.voted.detect { |u| u.voter_id == current_user.id }
    if user
      link_to '', post_vote_path(post, user, voted: true), method: :delete, class: 'like-link fas fa-thumbs-up liked'
    else
      link_to '', post_votes_path(post, voted: true), method: :post, class: 'like-link fas fa-thumbs-up'
    end
  end

  def dislike(post)
    user = post.unvoted.detect { |u| u.voter_id == current_user.id }
    if user
      link_to '', post_vote_path(post, user, voted: false), method: :delete,
                                                            class: 'like-link fas fa-thumbs-down disliked'
    else
      link_to '', post_votes_path(post, voted: false), method: :post, class: 'like-link fas fa-thumbs-down'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def background_update(user)
    render 'users/imageform' if user == current_user
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to posts_path do %>
    <div class="navbar-brand">
      <img src="https://user-images.githubusercontent.com/48393059/85749134-41884c80-b711-11ea-91c8-c833630f8b3d.png" alt='logo' />
    </div>
  <%end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <div class='input d-flex'>
        <button id='mydiv' class='fas fa-search'></button>
        <input type="text" name="search" id='searchinput'  class='search' placeholder="Search..">
      </div>
      <div class="dropleft">
        <span class=''></span>
        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class='fas fa-cog'></i>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to  "Profile", user_path(current_user), class: 'dropdown-item' %>
          <%= link_to  "Logout", '/logout', method: :delete, class: 'dropdown-item' %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class='sidebar position-fixed'>
  <div class='d-flex p-2 profile-top'>
    <%if current_user.image.attached?%>
      <%= image_tag(current_user.image, size: "50x50") %>
    <%else%>
      <div class='avatar'>
        <%= current_user.name[0] %>
      </div>
    <%end%>
    <h5 class='px-1 mx-auto my-auto'><%= current_user.name.upcase%></h5>
  </div>
  <div class='follow-counter f-row'>
    <div class='col-6'>
      <%=current_user.following.size%>
      <p>Following</p>
    </div>
    <div class='col-6'>
      <%=current_user.followers.size%>
      <p>Followers</p>
    </div>
  </div>
  <div class='side-links'>
    <%= link_to posts_path do %>
      <div class='d-flex'>
        <i class='fas fa-home'></i>
        <span>HOME</span>
      </div>
    <%end%>
    <%= link_to user_path(current_user) do %>
      <div class='d-flex'>
        <i class='fas fa-user'></i>
        <span>PROFILE</span>
      </div>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vyews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
    <script src="https://kit.fontawesome.com/5e0cee5c01.js"
            crossorigin="anonymous"></script>
  </head>
  <body>
    <div class=''>
      <%if current_user%>
        <%= render 'layouts/sidebar'%>
      <%end%>
      <div class='<%=current_user ? 'body' : '' %>'>
        <%if current_user%>
          <%= render 'layouts/navbar'%>
        <%end%>
        <%= yield %>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'index' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<section class='my-4 posts-section'>
  <h5 class='new-posts-today upcase'><%= !kind ? new_vyews(posts) : "ALL VYEWS"%></h5>
  <% posts.each do |post| %>
    <div class='d-flex w-100 post-main'>
      <div>
        <%if post.author.image.attached? %>
          <%= image_tag(post.author.image, size: '80x80') %>
        <%else%>
          <div class='avatar avatar-post'>
            <%= post.author.name[0] %>
          </div>
        <%end%>
      </div>
      <div class='post-body w-100'>
        <div class='d-flex'>
          <h5><%= post.author.name%></h5>
          <small class='ml-auto'><%= time_ago_in_words(post.created_at)%> ago</small>
        </div>
        <p><%= post.content%></p>
      </div>
    </div>
    <div class='d-flex mx-4 pb-4' >
      <div>
        <%= like(post)%>
        <%= post.voted.size%>
      </div>
      <div class='ml-auto'>
        <%= dislike(post)%>
        <%= post.unvoted.size%>
      </div>
    </div>
  <% end %>
</section>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%if notice%>
  <p id="notice"><%= notice %></p>
<%end%>
<div class='body-space'>
  <div>
    <div class='new-post-area mx-auto'>
      <h5>CREATE A VYEW</h5>
      <%= form_with(url: posts_path, local: true) do |f| %>
        <%= f.text_field :content, placeholder: 'compose a vyew', autocomplete: 'off' %>
        <%= f.submit %>
      <% end %>
    </div>
    <%= render 'posts/posts', posts: @posts, kind: false %>
  </div>
  <section class='end-sidebar px-3'>
    <h5>WHO TO FOLLOW</h5>
    <div class='follower'>
      <% @users.each do |u| %>
      <div class='position-relative'>
        <%= link_to user_path(u) do%>
          <div class='d-flex'>
            <div class='user-avatar-section'>
              <%if u.image.attached? %>
                <%= image_tag(u.image, size: '40x40', class: 'rounded-circle') %>
              <%else%>
                <div class='avatar'>
                  <%= u.name[0] %>
                </div>
              <%end%>
            </div>
            <div class='px-3 follow-text'>
              <p><%= u.name%></p>
              <h5 class='f-hashtag'>#<%= u.username%></h5>
            </div>
          </div>
        <%end%>
        <div class='follow-btn'>
        <%= link_to(user_followers_path(u), method: :post) do%>
        <%= image_tag 'https://image.flaticon.com/icons/svg/149/149145.svg' %>
        <%end%>
        </div>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_follow_profile.html.erb
     <% if user != current_user%>
  <%if current_user.following?(user)%>
    <div class='mt-3'>
      <%= link_to(user_follower_path(user), method: :delete) do%>
        <%= image_tag 'https://image.flaticon.com/icons/svg/149/149146.svg', class: 'img-options' %>
      <%end%>
    </div>
  <%else %>
    <div class='mt-3'>
      <%= link_to(user_followers_path(user), method: :post) do%>
        <%= image_tag 'https://image.flaticon.com/icons/svg/149/149145.svg', class: 'img-options' %>
      <%end%>
    </div>
  <%end%>
<%end%>

app/views/users/_followers.html.erb
      <% user.each do |f|%>
  <div class='position-relative'>
    <%= link_to user_path(f) do%>
      <div class='d-flex'>
        <div class='user-avatar-section'>
          <%if f.image.attached? %>
            <%= image_tag(f.image, size: '40x40', class: 'rounded-circle') %>
          <%else%>
            <div class='avatar'>
              <%= f.name[0] %>
            </div>
          <%end%>
        </div>
        <div class='px-3 follow-text'>
          <p><%= f.name%></p>
          <h5 class='f-hashtag'>#<%= f.username%></h5>
        </div>
      </div>
    <%end%>
    <% if @user == current_user%>
      <%if current_user.following?(f)%>
        <div class='follow-btn f-profile'>
          <%= link_to(user_follower_path(f), method: :delete) do%>
            <%= image_tag 'https://image.flaticon.com/icons/svg/149/149146.svg' %>
          <%end%>
        </div>
      <%else %>
        <div class='follow-btn f-profile'>
          <%= link_to(user_followers_path(f), method: :post) do%>
            <%= image_tag 'https://image.flaticon.com/icons/svg/149/149145.svg' %>
          <%end%>
        </div>
      <%end%>
    <%end%>
  </div>
<%end%>

app/views/users/_form.html.erb
<div class='row register-main'>
  <div class='col-lg-4 register'>
    <%= form_with(model: user, local: true) do |f| %>
      <h3>Create Account</h3>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div id="target"></div>
      <%= f.file_field :image, class: 'custom-file-input', id: "pictureInput" %>
      <%= f.text_field :name, placeholder: 'Name' %>
      <%= f.text_field :username, placeholder: 'Username' %>
      <%= f.email_field :email, placeholder: 'Email' %>
      <div class="actions">
        <%= f.submit 'Register' %>
      </div>
      <%= link_to  "Log in", new_usersession_path %>
    <% end %>
  </div>
  <div class='col-lg-7 ideas'>
    <h1> SHARE YOUR GREAT IDEAS AND THOUGHTS WITH THE WORLD! </h1>
  </div>
</div>

app/views/users/_imageform.html.erb
      <%= form_with(url: user_path(@user), method: :patch, local: true) do |f| %>
  <%= f.file_field :cover, class: 'custom-background-input', id: "pictureInput", onchange: 'this.form.submit();' %>
<%end%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%if notice%>
  <p id="notice"><%= notice %></p>
<%end%>
<div class='body-space'>
  <div class='user-top'>
    <div class='cover-image' style='background: url(<%= @user.cover.attached? ? url_for(@user.cover) : 'https://images.pexels.com/photos/1209751/pexels-photo-1209751.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'  %>)40% '>
      <%= background_update(@user)%>
    </div>
    <nav>
      <div class="nav profile-tab d-flex" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria- 
      selected="true">VYEWS</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria- 
    selected="false">FOLLOWERS</a>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria- 
      selected="false">FOLLOWING</a>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria- labelledby="nav-home-tab">
        <div class='hashtag'>
          <div class='new-post-area mx-auto'>
            <h5 class='upcase'>VYEWS BY <%=@user.name%></h5>
            <%= form_with(url: posts_path, local: true) do |f| %>
              <%= f.text_field :content, placeholder: "##{@user.username}", autocomplete: 'off', disabled: true %>
            <% end %>
          </div>
          <%= render 'posts/posts', posts: @user.posts.reverse, kind: true %>
        </div>
      </div>
      <div class="tab-pane fade followers-tab" id="nav-profile" role="tabpanel" aria- 
     labelledby="nav-profile-tab">
        <%= render 'users/followers', user: @user.followers%>
      </div>
      <div class="tab-pane fade followers-tab" id="nav-contact" role="tabpanel" aria- 
    labelledby="nav-contact-tab">
        <%= render 'users/followers', user: @user.following%>
      </div>
    </div>
  </div>
  <section class='end-sidebar'>
    <div class='user-avatar-section'>
      <%= render 'users/follow_profile', user: @user %>
      <%if @user.image.attached? %>
        <%= image_tag(@user.image, size: '90x90', class: 'rounded-circle') %>
      <%else%>
        <div class='avatar big-avatar'>
          <%= @user.name[0] %>
        </div>
      <%end%>
      <%= image_tag('https://image.flaticon.com/icons/svg/3039/3039357.svg', class: 'img-options') %>
    </div>
    <div class='centered user-name'>
      <h4 class='upcase'><%= @user.name%></h4>
      <h5>#<%= @user.username%></h5>
    </div>
    <div class='profile-followers-tab'>
      <div>
        <h5><%= @user.posts.size%></h5>
        <p>VYEWS</p>
      </div>
      <div>
        <h5><%= @user.followers.size%></h5>
        <p>FOLLOWERS</p>
      </div>
      <div>
        <h5><%= @user.following.size%></h5>
        <p>FOLLOWING</p>
      </div>
    </div>
    <div class='followed-by px-3'>
      <h5>FOLLWED BY</h5>
      <%= render 'users/followers', user: @user.followers%>
    </div>
  </section>
</div>

app/views/usersessions/new.html.erb
<div class='login register login'>
  <%= form_with(url: usersessions_path, local: true) do |f| %>
    <h3>Log In</h3>
    <div id="target"></div>
    <%= f.text_field :username, placeholder: 'Username' %>
    <div class="actions">
      <%= f.submit 'Login' %>
    </div>
    <%= link_to  "Sign up", new_user_path %>
  <% end %>
</div>